version: '3.8'
services:
  redis:
    image: redis:7
    ports: ['6379:6379']
  dask-scheduler:
    image: daskdev/dask:latest
    command: dask-scheduler
    ports: ['8786:8786','8787:8787']
  dask-worker:
    image: daskdev/dask:latest
    command: dask-worker tcp://dask-scheduler:8786 --nthreads 2 --memory-limit 4GB
    depends_on: ['dask-scheduler']
